### ISSUE TITLE
Counting randomized barcodes with known flanking sequences.

### ISSUE THREAD

**Issue by j-andrews7** [crisprVerse/screenCounter#1]
I've got a use case where we have a screen with random 20bp barcodes - it'd be convenient to ignore the `choices` parameter and have both the barcodes and corresponding counts returned just based on the flanking sequences.

**Comment by LTLA** [comment]
Seems reasonable. Should be easily possible but I need to poke through the C++ code to remind myself of what to do.

**Comment by LTLA** [comment]
Single-end counter added in 97311edaf3614aab1fe6680c8b603772b5727918, see `?countRandomBarcodes` for details.

**Comment by j-andrews7** [comment]
Perfect, appreciated as always.
